jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Inject adminPassword into parameters
        run: |
          sed -i "s/\${{ secrets.ADMIN_PASSWORD }}/$(echo ${{ secrets.ADMIN_PASSWORD }})/" ./bicep/main.parameters.json

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: 'NEW'
          template: ./bicep/main.bicep
          parameters: ./bicep/main.parameters.json
