name: Bicep Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Bicep to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: 'NEW'  # Ensure the resource group 'NEW' exists or modify as needed
          template: bicep/main.bicep
          parameters: |
            location=eastus
            Password=${{ secrets.ADMIN_PASSWORD }}  # Make sure this parameter is properly defined in the Bicep template
