name: Azure Bicep Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: 'NEW'
          template: ./bicep/main.bicep
          parameters: adminUsername='azureuser' adminPassword='${{ secrets.ADMIN_PASSWORD }}'
          deploymentName: 'fullInfraDeploy'
