name: Azure Bicep Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --resource-group myResourceGroup \
          --template-file main.bicep \
          --parameters location="EastUS" \
                       vnet1Name="vnet1" \
                       vnet2Name="vnet2" \
                       vm1Name="vm1" \
                       vm2Name="vm2" \
                       storageAccount1Name="storage1" \
                       storageAccount2Name="storage2" \
                       adminUsername="azureadmin" \
                       adminPassword="${{ secrets.ADMIN_PASSWORD }}"
